### PR TITLE
Created desktop version

### PR DESCRIPTION
**Pull request by SebastianSolisFenger**
Created desktop version of the project based on the following requirements: 

- Use media queries in your CSS file to make your desktop version look like the template you selected (Desktop: 768px or wider).

- In order to layout the elements on the page, use Grid and Flexbox.

- You don't need to implement any functionality that requires JavaScript.

- You must replicate the design as much as possible (e.g., font, colors, images, tests, margins) using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @SebastianSolisFenger, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Good PR description and title

## Required 
- [x] Kindly add a description of your project to the readme file.
- [x]  Kindy fix the background image for desktop and mobile versions according to Figma design.
- Your desktop version:
Screenshot 2022-03-24 at 12 21 02 AM

- Figma desktop version:
Screenshot 2022-03-24 at 12 22 26 AM

- Your mobile version:
Screenshot 2022-03-24 at 12 21 41 AM

- Figma mobile version:
Screenshot 2022-03-24 at 12 23 09 AM

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SebastianSolisFenger** [comment]
Hi, @sja-thedude. I appreciate your feedback. Never a reviewer told me anything about the background images, though I've tried my best to make it look as similar as possible to the Figma.

Do you have any suggestions? I've really gotten to a point in which I don't know what else to do. 

Moreover, I don't understand what do you mean by:

( "You can also consider:

x
y
z
" )

Thanks.

**Comment by sja-thedude** [comment]
Hi @SebastianSolisFenger 
You can also consider is just a part of template which I forgot to remove. You have done a great job on this project! You can try to place the background image of a particular section in css of that particular section.

**Review by gemmen29 — APPROVED** [review]
Hi @SebastianSolisFenger, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions:
- [ ] Kindly add a title of the project in your README file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
